### ISSUE TITLE
wcf 与 wrest 远程部署通信timeout

### ISSUE THREAD

**Issue by r00tuser111** [opentdp/wrest-chat#62]
求助：wcf 与 wrest 远程部署通信timeout

在windows 启动wrest.exe，配置如下：

```
# 运行日志
Log:
    Dir: logs # 存储目录，非必要不修改
    Level: info # 记录级别，debug|info|warn|error
    Target: stdout # 输出方式，both|file|null|stdout|stderr

# Wcf 服务
Wcf:
    Address: 0.0.0.0:7602 # 若使用外部地址，请删除 WcfBinary 选项
    MsgPrint: false # 是否将消息输出到控制台，可用于调试
    MsgStore: true # 是否将消息写入数据库，用于防撤回和统计
    MsgStoreDays: 7 # 启动时清理n天前的消息，0 表示不清理
    WcfBinary: wcf.exe # wcf 二进制文件路径，留空则不托管（Linux 必须留空）

# Web 服务
Web:
    Address: 127.0.0.1:7600 # 监听地址，外网访问修改为 0.0.0.0:7600
    PushUrl: "" # 消息推送地址，一行一个，留空则不启用
    Storage: storage # 附件存储路径，非必要不修改
    Swagger: true # 是否启用内置接口文档和调试工具
    Token: "" # 使用 Token 验证请求，留空则不验证
```

windows的IP为：`192.168.1.103`

在linux上启动 wrest web服务，配置如下：
```
# 运行日志
Log:
    Dir: logs # 存储目录，非必要不修改
    Level: info # 记录级别，debug|info|warn|error
    Target: stdout # 输出方式，both|file|null|stdout|stderr

# Wcf 服务
Wcf:
    Address: 192.168.1.103:7602 # 若使用外部地址，请删除 WcfBinary 选项
    MsgPrint: false # 是否将消息输出到控制台，可用于调试
    MsgStore: true # 是否将消息写入数据库，用于防撤回和统计
    MsgStoreDays: 7 # 启动时清理n天前的消息，0 表示不清理

# Web 服务
Web:
    Address: 0.0.0.0:7600 # 监听地址，外网访问修改为 0.0.0.0:7600
    PushUrl: "" # 消息推送地址，一行一个，留空则不启用
    Storage: storage # 附件存储路径，非必要不修改
    Swagger: true # 是否启用内置接口文档和调试工具
    Token: "" # 使用 Token 验证请求，留空则不验证
```

windows输出log为：
```
time=2024-06-05T14:00:59.477+08:00 level=WARN msg="wcf starting ..."
time=2024-06-05T14:00:59.480+08:00 level=WARN msg="wcferry/wcf.exe start 7602"
time=2024-06-05T14:01:01.536+08:00 level=WARN msg="pbSocket dial" server=tcp://0.0.0.0:7602
time=2024-06-05T14:01:02.543+08:00 level=WARN msg="pbSocket dial" server=tcp://0.0.0.0:7603
```

linux上输出log为：
```
time=2024-06-05T13:53:38.983+08:00 level=WARN msg="pbSocket dial" server=tcp://192.168.1.103:7602
time=2024-06-05T13:53:43.986+08:00 level=ERROR msg="receive time out"
time=2024-06-05T13:53:44.986+08:00 level=WARN msg="pbSocket dial" server=tcp://192.168.1.103:7603
```

目前排查了端口联通问题，确认端口是通的，但还是time out。
